### ISSUE TITLE
Plugin Exits When Unable to Connect to Honeywell

### ISSUE THREAD

**Issue by ayanm00** [NorthernMan54/homebridge-tcc#45]
Hi again NorthernMan54,

Just wanted to inform you of another issue I discovered while Honeywell went down this past week. The plugin failed to connect (since Honeywell was down), and it just hung there for a few minutes and then self-exited Homebridge. Wouldn’t it be better if continued to try and reconnect so that when Honeywell comes back up, the plugin would connect again?

Thanks,
ayanm00

**Comment by mhall** [comment]
I am seeing frequent issues along these lines.  Although the plugin does not completely crash, after an issue connecting to Honeywell it gets into a weird state that disables _all_ Homebridge plug-ins (shows “Not Responding” in Home app) until Homebridge is restarted. Have you had a chance to begin the refactor work?

**Comment by NorthernMan54** [comment]
Is your homebridge configured to auto start/restart after issues? I use systemd for mine and don’t see this happening.

**Comment by mhall** [comment]
I use systemd as well — the issue here is that the homebridge service does not crash and so does not get restarted. However, after a Honeywell issue shows up in the logs, it stops communicating in some way that causes all Homebridge-powered accessories to show “Not responding” in the Home app. I have to manually restart the service to restore connectivity. Are you seeing Honeywell-related errors in your service logs?

**Comment by NorthernMan54** [comment]
Can you share some logs, as your issue appears to be different that the original issue.  In the original issue, homebridge was exiting and restarting, but it appears for yourself to just hang.

**Comment by mhall** [comment]
Apologies for the delayed response. I tracked the hangs to an unrelated network issue, so this plugin is not to blame. Thanks!

**Comment by NorthernMan54** [comment]
Tks for the update
