### ISSUE TITLE
Add Humidification Accessory if system supports humidifier/dehumidifier controls

### ISSUE THREAD

**Issue by kylerove** [NorthernMan54/homebridge-tcc#98]
I'm working to add a humidifier-dehumidifier accessory if it is supported. I don't have access to the API to know what to send back to MyTotalConnect/Honeywell on changing the mode or humidification set points. Am I correct that `ChangeThermostatMessage` serves this function in `tccMessage.js`, to communicate intended/desired changes back to the API?

I've tried googling for any insight into the humidification side of the API without luck. This is probably the last hold up before I proceed with testing, refine and send over a pull request.

**Comment by NorthernMan54** [comment]
For the api I had reverse engineered the iPad app api with the Charles proxy last year.  But since then they have released an update that prevents from working now.

If you google the endpoint, you can find a couple of other initiatives that leverage the same endpoint.  Not sure if they support humidifier controls.

one other thought, have you looked at other TCC integrations ie home assistant to see what they do?

**Comment by kylerove** [comment]
I did some digging and came up empty. Home Assistant integration uses a library that does not have humidity control. When I have time, I might do some digging on their website to see if that is illuminating.
